### ISSUE TITLE
Unit with immune to poison can still be poisoned

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#125]
If a unit is given both a `Scourge of All Living` and an `Intoxicator`, that unit is still poisoned at the start of the turn and takes damage even though they should be immune to poison from the Intoxicator item.

**Comment by Dugy** [comment]
The ability _immune to poison_ is described explicitly as _poisonous attacks have no effect._ Because this is not an attack, it's not covered.

I am not being a rules lawyer here, this is entirely intentional. There were many complaints about undead being underpowered by this campaign, so there are some items specially made for them.

**Comment by arobinson** [comment]
Makes sense, was wondering when I filed it, especially it is not specifically a poison description, but cancer. Thanks. Perhaps the Cancer ability could make this more clear that it is not resistable?
