### ISSUE TITLE
Belzebub can be summoned twice

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#14]
First of all thank you for creating (and supporting!) this awesome piece of campaign.

Whenever unit is placed on Belzebub-summoning shrine, dialog is triggered when player can summon Belzebub.
This happens even if there was other Belzebub already summoned on same map, even if this Belzebub is still alive.
IMO this shrine should not stay intact after usage - should either disappear or become passive

LoTI 3.1.23, Wesnoth 1.12.5

**Comment by matsjoyce** [comment]
Can you retest using the git version? It looks like that has already been fixed in https://github.com/Dugy/Legend_of_the_Invincibles/commit/d573c1ce9fd3823a3282b223ba28cec1ac430915

**Comment by arodiss** [comment]
@matsjoyce 
Sorry for stupid question, but is it safe to upgrade? I currently have campaign downloaded from add-on server and don't want to loose my savefiles.
And from which point should I start? Restart scenario, load save before B arrives, load save after?

**Comment by matsjoyce** [comment]
Your old save files should not be corrupted if you upgrade, however they may not work once you have upgraded (you will be able to use them if you revert your LotI version back). I don't know how many breaking changes have made since 3.1.23 and how much they would break, so you'll need to wait for @Dugy to reply to find out.

**Comment by arodiss** [comment]
@matsjoyce 
Thank you. I will upgrade, restart scenario and write back

**Comment by arodiss** [comment]
Works correctly with master version
