### ISSUE TITLE
Some issues with documentation

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#18]
- [x] "Heart of Darkness" AMLAs don't have weapon specials specified (doom, trickery, mayhem)
- [x] Fencer unit advancements has bogus "09" perpended to label
- [x] Soul eater and god spells don't have all specials listed (did not check it but if there are no specials eg fire blast would be weaker than trivial fireball - same for thunder, blizzard, meteor firestorm, arctic blast)
- [x] First advancement from Book of fireballs claims to "able to cast an incinerating fireball" but incinerate special is not listed
- [x] There are two "lawful" abilities listed - one with daily bonus and nightly penalty, other with bonus only. If these are different better give them different names to avoid confusion
- [x] All units which have upgradable charge (Stormrider, Dragon rider, Lunatic knight, Grim knight, Prophet) have weird upgrade description: "remove weapon special charge, add weapon special charging" - even though that on abilities page only "charge" is present, no "charging". One way to fix this is to act same as with heals / regeneration / conviction / despair : to have ability charge (xX), ie "charge (x2)", "charge (x2.5)", "charge (x3)". Another way is to do like backstab / illumination / darkens, ie to have fully different names like "charge", "greater charge", "uber charge"

**Comment by matsjoyce** [comment]
OK, looks like this one is for me @Dugy.

**Comment by Dugy** [comment]
- I don't understand what do you mean with _is not listed_. There doesn't seem to be any error with these items
- The 09 prepended is special to Efraim and Phillip who have special progression, they are not usual fencers
- I have not found any second ability named _lawful_
- I agree that _charging_ could follow the usual habits and use meaningful names; I will do it, but later, if you want, you can make a pull request

**Comment by matsjoyce** [comment]
@arodiss:
 1. Heart of Darkness: What do you mean exactly? I can't find any HoD entry specifying those specials.
 2. Fixed.
 3. Fixed.
 4. Fixed, same bug as 3.
 5. Fixed. This happens because of the lawful and chaotic special, which uses one ability for the day bonus and one for the night. I've changed the script so that it merges abilities like this.
 6. Fixed. I also found that deathaura and careful were broken in the same way.

Thanks for reporting these, as I'm sure there are quite a few errors on the wiki but I don't have enough patience to go through each entry to look for bugs. I haven't updated the wiki quite yet as I am working on a automatic upload thing so that I don't have to keep Ctrl-A + Ctrl-Ving.

**Comment by Dugy** [comment]
@matsjoyce Heart of Darkness is an item that unlocks an AMLA path, these advancements are in units/amla.cfg.

**Comment by matsjoyce** [comment]
@Dugy Yes, I know. I mean that looking at all the entries (item and ALMAs) I can't find any of the specials he mentioned.

**Comment by matsjoyce** [comment]
@arodiss New update are now live.

**Comment by arodiss** [comment]
@matsjoyce @Dugy 
Thank you so much!

**Comment by matsjoyce** [comment]
@arodiss Currently it is in a gist at https://gist.github.com/matsjoyce/bd13afe1a50882436103a2f506991f3d but I can turn it into a repo if you want.

**Comment by Dugy** [comment]
Maybe a repo would make sense, since without it, its problems are reported here. Since the wiki is not my work and I am not very good at python (I would use the _golden hammer_ C++ for that if it was my project), I can't help with that much.

**Comment by matsjoyce** [comment]
Well, I could use C++, but the amount of code would be rather scary... Although I could use Boost.Spirit then. I've created a new repo at https://github.com/matsjoyce/LotIWikiGen, I'll add the code there once I have finished breaking things.

**Comment by Dugy** [comment]
@matsjoyce I am not suggesting you to use C++. Just telling that if I tried to maintain it, the code would age really fast, becoming a worse ravioli than LotI is.

**Comment by matsjoyce** [comment]
It's already ravioli so I wouldn't worry about that. 😁

**Comment by matsjoyce** [comment]
@arodiss OK, PRs to https://github.com/matsjoyce/LotIWikiGen if you can understand my code...

**Comment by MPagel** [comment]
Re: lawful.  I was under the impression that the lawful weapon special had no night time penalty, just a daytime bonus.  Whereas the character trait lawful means that there's a nighttime penalty and a daytime bonus.

related: It's not clear to me what is meant by (paraphrasing) "illuminates even the day" means.  I take it that lawful units get a greater than 25% bonus and chaotic units get a greater penalty, but it doesn't spell it (or give the %s) out in the game help that I've noticed.

only tangentially related (this is a greater Wesnoth issue, rather than LotI): I've never understood why the liminal units get penalty day and night but no bonus at sunset/rise. I guess this can be compensated for by increasing the base damage of the unit, but then the penalty for off-ideal time isn't as great as for day vs night for lawful or chaotic. The whole sunset and sunrise being 1/3 of a day thing is a little weird, but it is an alternate world afterall.

**Comment by arodiss** [comment]
@matsjoyce 
Thank you for repo
If you add some rudimentary docs, eg the exact command how do you run the generator and where do you  grab raw info - this would be highly appreciated.
Without this any effort to improve will be blindfolded

**Comment by matsjoyce** [comment]
Sure, I'm right on it.

**Comment by matsjoyce** [comment]
@arodiss OK, is that enough? I also de-monolithed it, so it should be easier to handle.

**Comment by arodiss** [comment]
Thank you @matsjoyce !
Provided documentation is sufficient
