### ISSUE TITLE
Dragon Rider bite does not gain +attack

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#228]
A non-weapon item that grants an extra attack (ex Dark Helm) no longer adds another attack to the Dragon Rider's bite attack. It does add to his spear attack. Previous to the lua implementation, it added to both.

**Comment by dalong76** [comment]
It also does not get suck

**Comment by Dugy** [comment]
Just a note to find it easier, the change was supposedly made in commit 5d9fe5a

**Comment by Dugy** [comment]
I don't know about it ever working to influence the number of attacks or add suck to his bite attack. Furthermore, looking at the deleted file, I can't find a way how could it influence that attack.

Only set effects and advancements can and could influence that attack. The effect of that helmet isn't a set effect.

**Comment by dalong76** [comment]
I'll call it a bug in the old version and close this then.
My saying it used to work is from Wesnoth 1.12.6. I only switched to current Wesnoth a few weeks ago. I did often update LotI code from github, and I don't see why the stats.cfg I was actually using with 1.12.6 would have worked differently, but it isn't worth chasing.

I'm surprised it doesn't gain suck though. I thought anything not a spell with physical damage gained suck. What non-spell attacks besides dragon bite don't benefit from suck?

**Comment by Dugy** [comment]
That property affects all _weapons._ That used to include only actual weapons, but because some units sucked due to inability to use weapons, some rather exotic craft-only weapons (metal claws, spiritual essences, ...) were implemented to give them something to equip, making most non-weapon attacks act as if they used default weapons.

However, there are still a few attacks that do not count as weapons and still aren't spells. If I recall correctly, they have significantly better AMLA bonuses to compensate and I would like to keep it that way for diversity.

If you have good arguments why should it be done differently, go on. I am reputed for listening to opinions of other people, after all.
