### ISSUE TITLE
neutral side variables not cleared

### ISSUE THREAD

**Issue by dalong76** [Dugy/Legend_of_the_Invincibles#251]
My saved games tend to have an accumulation of variables with names like this:
side_1_original_team_name
side_1_original_user_team_name
side_2_original_team_name
side_2_original_user_team_name
all the way up to side 17.
I'm confident these come from the macro NEUTRAL_SIDE in utils.cfg, but I'm not sure why they don't get cleared.

**Comment by Dugy** [comment]
They do come from there, but I am also not quite sure where do they come from.

**Comment by edwardspec** [comment]
This macro is no longer needed, it's possible to specify multiple teams in team_name= attribute of `[side]` WML. This is already used in Gladiators.

**Comment by Dugy** [comment]
I could replicate the problem, but the thing is even more bizarre than I thought before, because:

- Other variables supposed to be deleted in that end-scenario event are properly deleted
- side_17_original_team_name is indeed defined, but `{NEUTRAL_SIDE 17}` or `{NEUTRAL_SIDE 1}` aren't instantiated anywhere

**Comment by Dugy** [comment]
I have found the cause, but I decided to remove all instances of the macro and replace it with the newer way of dealing with the problem instead of fixing it.

**Comment by dalong76** [comment]
For general knowledge, what was the bug that caused side 17?

**Comment by Dugy** [comment]
It created such variables for every side present in the scenario, not only for sides that were neutral.
