### ISSUE TITLE
lua/wml-tags.lua:1408:bad argument #2 to 'concat' (string expected, got translatable string)

### ISSUE THREAD

**Issue by johncburr** [Dugy/Legend_of_the_Invincibles#26]
stack traceback:
[C]: in function 'table.concat'
lua/wml-tags.lua:1408:in local 'cmd'
lua/wml-utils.lua:145:in field 'handle_event_commands'
lua/wml-flow.lua:138: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml/message.lua:409: in local 'cmd'
lua/wml-utils.lua:145: in field 'handle_event_commands'
lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

BfW ver. 1.13.7

Happens when in the "Transmute gems" menu and you use the option, "Better let such experiments be"

**Comment by Dugy** [comment]
This reeks of a bug in Wesnoth. I reported it at https://github.com/wesnoth/wesnoth/issues/1682

**Comment by johncburr** [comment]
It's worse. Appears to give the same error whenever you try to craft anything, armour or weapon. I'll bet they made something non-translatable that used to be translatable. So your script would now be "using the wrong data type."

**Comment by Dugy** [comment]
It was confirmed as a bug in the game and was placed on the 1.13.8 milestone (it means that it is considered to be a serious bug and 1.13.8 can't be released before it's fixed). I cannot provide any workarounds and I don't know how to fix it without an extensive research of the problem.

**Comment by johncburr** [comment]
That's cool. I'll keep playing to see what else I can find.

**Comment by CelticMinstrel** [comment]
If you need a workaround, you could provide a custom implementation of the `table.concat` function... that said, 1.13.8 is expected to be released this weekend (though there's always a chance it gets postponed again) and the bug is already fixed (by not using `table.concat`), so it may not be worth it.

**Comment by Dugy** [comment]
I thought this error is deeper, preventing also string concatenation. Also, I didn't know I can replace a function with a custom function with the same name.

Also, because I do not have much time at the moment, I will better wait for this weekend's release. Thanks for replying.

**Comment by CelticMinstrel** [comment]
Nah, the issue was that `table.concat` does not actually use the Lua concat operator or even the `__tostring` metafunction. Translatable strings already overloaded both of those, so all I had to do was not use `table.concat`.

You can replace _almost anything_ built-in in Lua with your own version, or even extend things by saving the original under a different name and calling it from the new version.

**Comment by Dugy** [comment]
Aha, I didn't know that. I thought it was something deeper in the engine. Thanks.

**Comment by johncburr** [comment]
I downloaded 1.13.8 and also the latest of your files this morning. The problem appears to be resolved.
