### ISSUE TITLE
Ooops, this is only temporary, or something went wrong

### ISSUE THREAD

**Issue by arodiss** [Dugy/Legend_of_the_Invincibles#29]
During AI turn two of m units got levelup with AMLA
I was able to select AMLA for one unit, but for other I got no AMLS selection screen. In "unit information" I see beforementioned message instead of last AMLA

**Comment by Dugy** [comment]
The problem is that this kind of problem is very bug prone and I am afraid that I will fix it while breaking something else. It happened to me multiple times in the past.

The code is entirely rewritten for 1.13 and as 1.14 is nearby, I'd prefer not to start another episode of creating new bugs, fixing them while reitruducing more.

**Comment by arodiss** [comment]
@Dugy 
No problem - though annoying this problem is easy to workaround
Feel free to close this
