### ISSUE TITLE
 Make "gem found" window non-blocking (at least in MP)

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#320]
A blocking gem window is uncomfortable in MP because players need to click it to go through, so a player can't go afk and wait until the turn bell rings to go back to his move, because the gem window will block the game until he clicks.

**Comment by Dugy** [comment]
Are the gem windows different from the item windows? Do you mean that all players have to wait until all players click on the pickup window to continue?

That seems to be a serious problem. That window is mostly cosmetic, finding its source and replicating it in lua inside a synchronised section should fix it. It could also make the code look more readable since the `[object]` tag has little to do with its effect on the unit.

**Comment by Discontinuum** [comment]
Well, not so dire, others don't have to wait everyone to proceed. But still it is somewhat annoying when you need to click through on someone's else turn. When it's your turn, it's okay, but when it's not your turn and you have to click, not nice. Can't go afk and wait for the turn bell without checking, as I mentioned. Also tiresome for observers to click through all gems to go through the replay

**Comment by Discontinuum** [comment]
Not relevant after #323
