### ISSUE TITLE
Some effects not apply to all targets of AoE attacks

### ISSUE THREAD

**Issue by agguser** [Dugy/Legend_of_the_Invincibles#421]
It seems that LotI-specific effects (e.g. incinerate, suck) do not apply to all targets of AoE attacks (e.g. whirlwind, cone), but apply only to single target (the clicked one). This is unlike Wesnoth effects (e.g. poison, drain), which apply to all targets. Is this a bug or an intention?

**Comment by Dugy** [comment]
It is an intention. It would be too powerful otherwise.

Historically, the area of effect attacks were written to support most effects. However, it soon became way too easy to wipe out rooms of enemies with AoE attacks while draining large amounts of hitpoints back, allowing to beat scenarios with two superhero leaders. First, I heavily restricted the availability of drain, adding much weaker suck and leech instead. They had to be further toned down to minimise the options to fully heal from low health in one attack. Any powerful AoE attack with stacked healing would allow full heal with single attack, so it's not supported. Other effects I added later, like infect or incinerate, were not made to work with AoE because the synergy was too powerful for the ease of achieving it.

**Comment by agguser** [comment]
Thanks for the clarification. So I will close this issue.

By the way, LotI is fun. Thank you for making it. Hope there would be "Part III"!

**Comment by Dugy** [comment]
Sorry, a Part III is very unlikely.

**Comment by Discontinuum** [comment]
Sorry for a slight offtopic, would it be possible to upload Affably Evil and The Beautiful Child on 1.16? I miss them. You've uploaded Kill the King, that's nice, but those two I liked as well

**Comment by Dugy** [comment]
Done. I haven't playtested the entire campaigns, though.

**Comment by Discontinuum** [comment]
I wish they were on github so I could pull-request fixes. Would it be possible to have them on github as well?

**Comment by Dugy** [comment]
I don't want to have 3 additional repositories for them because they are quite related. I could put them as subdirectories into the github repository and make the game ignore them, making them accessible through links in the add-ons folder. I wonder how complicated it would be to set up.
