### ISSUE TITLE
Misc improvements from the forums

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#52]
The following things have been mentioned on the forums, making a list here so that they are not forgotten:

 - [x] In the scenario "Umbra" the narrator says "Seeing their divine incarnation, all the evil elves were inspired and their power in combat grew." but nothing happens. Maybe the elves should be given a buff? https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619431#p619421
 - [x] Efraim's fury attacks have the damage type blade even when the original weapon changes to another damage type. Is this intentional? https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619431#p619396
 - [x] The white mages in the scenario "Gods" cannot be hit, even after discovered. https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619431#p619421
 - [x] In the scenario "Umbra" [the bosses do not drop](https://wiki.wesnoth.org/LotI_Scenarios#05_.E2.80.93_Umbra). Is this intentional? https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619431#p619421
 - [x] At the end of 'A long way home' Lethalia and Efraim part ways, with Lethalia saying that she goes to the forest for reinforcements. But she doesn't bring any reinforcements when arriving at Ogira. https://forums.wesnoth.org/posting.php?mode=quote&f=8&p=619421#pr619422

Low priority:

 - [x] In the scenario "The Army of Darkness" Lethalia says "... We must help and we must succeed." Failure doesn't actually matter so this could be shortened to "... We must help." https://forums.wesnoth.org/posting.php?mode=quote&f=8&p=619421#pr619421
 - [x] In the scenario "The Army of Darkness" elves can be recruited even though they are pretty much in thick enemy territory. https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619436#p619436

**Comment by Dugy** [comment]
1 (divine incarnation) - It was probably referring to his leadership. Reworded it for clarification.
2 (Efraim's fury) - Looks intentional. It definitely has some implications that can be used.
3 (mages impossible to hit) - They aren't supposed to die.
4 (bosses don't drop) - Intentional. Not sure why I set it so, though.
5 (cake is a lie) - Reworded.
6 (we must succeed) - Reworded the whole line. It did not make much sense anyway.
7 (recruitment among enemies) - It's done pretty much everywhere in Wesnoth. I am classifying it as an acceptable break from reality.
