### ISSUE TITLE
advance_to is not adjusted in 1.13

### ISSUE THREAD

**Issue by matsjoyce** [Dugy/Legend_of_the_Invincibles#56]
Forum post: https://forums.wesnoth.org/viewtopic.php?f=8&t=32384&p=619699#p619699
When a unit advances in 1.13, `{UPDATE_STATS}` is not used as only the LUA code is executed. The result is that a unit still has `Advancing{TYPE}` advancements resulting in duplicated upgrades:

![image](https://user-images.githubusercontent.com/6631310/32662031-0b6b9816-c621-11e7-8037-e6722acb9ded.png)

On a side note, why do we have an `Advancing{TYPE}`? Can't we just use the normal unit type?

**Comment by Dugy** [comment]
This always happens when somebody creates a unit with debug mode. It's extremely unlikely that some recent change in 1.13 broke it.

**Comment by matsjoyce** [comment]
I can still reproduce it with recruited units leveling normally.

**Comment by Dugy** [comment]
So it's caused by the differing advancement code between 1.12 and 1.13. I don't have time to have a closer look at it right now, but simply adding the UPDATE_STATS macro at the right place could fix it. UPDATE_STATS not being called has other effects such as missing weapon specials given by equipped armour.

**Comment by matsjoyce** [comment]
OK, I've added that and it works fine now. Is there any reason to have the two different unit types?

**Comment by Dugy** [comment]
Are you sure it does not break under different circumstances and that the change has no effect on 1.12?

The secondary unit type is useful to hold the advancements. For reasons unknown, units in game cause terribly framedrops if they have a lot of advancements. For known reasons, it terribly bloats save files. So the units have no advancements, before advancing, their type changes so that they could pick one and then they change the type back.

**Comment by matsjoyce** [comment]
That block is wrapped in a `#ifver` so the change won't even exist in 1.12. The change is in a `post advance` event, so it shouldn't affect anything else.

**Comment by Dugy** [comment]
All right.

**Comment by gfgtdf** [comment]
> For reasons unknown, units in game cause terribly framedrops if they have a lot of advancements

It's actuall not that unknown, whenever a unit is drawn it calculates whether the unit has still a possible advancement ( to determine the color of the xp bar iirc) which means is basicially iteraters though all posible advenements and does all the require_amla etc. checks which then iterates though all taken amlas etc. we just didn't bother to improve this becasue many advancements woudl be bad anyways because of the savefile issue.

**Comment by Dugy** [comment]
@gfgtdf That is why the unit type is supposed to shift into a different one for the time of advancement. The advancements are neither processed while rendering nor stored in save files. However, it appears that a change in the way advancement events are fired broke it.
