### ISSUE TITLE
Subtle problem caused by the use of get_type_advancement in effect_containers (unitdata.lua)

### ISSUE THREAD

**Issue by Discontinuum** [Dugy/Legend_of_the_Invincibles#560]
So, https://github.com/Dugy/Legend_of_the_Invincibles/blob/2e08f7f943fef05ed2260b198ee0155a8aa5a2a5/lua/unitdata.lua#L60-L77 ``get_type_advancement`` local function gets the contents of an advancement from the unit model (AdvancingType or Type) by id, if there is no such advancement, it returns the table with just its id. 

I don't understand though why it's used here in effect_containers https://github.com/Dugy/Legend_of_the_Invincibles/blob/2e08f7f943fef05ed2260b198ee0155a8aa5a2a5/lua/unitdata.lua#L240-L247

We have already got the contents on line 240, why would we need to override it on 246? It would only make sense if actual AMLAs of units were stored with just their ids in "modifications" section, so we had to go in the model to parse the effects. But actual acquired AMLAs always stored in their full form (otherwise Wesnoth wouldn't see default effects like +hp, +damage, etc) if I understand correctly.

Where this causes trouble: right now I'm developing a mod that allows all units to benefit from LotI AMLAs and books (because right now if a unit doesn't have a special LotI upper level, neither legacies nor books can be used. Like with the Steel Scourge that you free in the prison in Akula's dungeon). My idea was to consider which legacy and which books this unit has and dynamically add required advancements in a "pre advance" event. The problem is that because of the use of ``get_type_advancement`` many interesting LotI effects, like penetration or bonus attacks, don't work: ``get_type_advancement`` can't obviously find the newly added advancement in the non-LotI unit type, it returns ``{ id = advancement_id } `` table and stats.lua don't see effects. If I hack the save file and turn all those added advancements into objects , everything works as it should (because for ``[object]`` we only mess with ``contents`` only if it's an item that can have set effects).

**Comment by Discontinuum** [comment]
Hm, I see that this model was first introduced in this commit for "effects" https://github.com/Dugy/Legend_of_the_Invincibles/commit/863a49884b5e81fcca5583693b96d075f209d39c (and later "effect_containers" was coded by analogy). The description exactly says that "the idea is to remove full [advancement] tags from the units at some point in the future". But 4 years passed and this future didn't come. Should we still stick to it?

**Comment by Dugy** [comment]
The goal of that was to reduce the size of save files, which are rather large in LotI. It had to be left there for years so that there would be very little players wanting to use save files from before the time it was started. Of course, I have forgotten the whole plan at some point. Still, I'd prefer to stick with it.

If you want to create a mod that changes something, you don't need to do it in a hacky way. We can add some mechanism that would allow you to do what you want without any tricks. If your problem is the derivation of the unit type that has the advancements, we can change the way it is derived so that there would be an alternative way of doing it.

**Comment by Discontinuum** [comment]
Alright, the plan is reasonable, I understand your wish to stick to it. Maybe we may fix the implementation of this place though, as right now it has two flaws. First, as all advancements continue to be stored in the full form, it's right now useless. By itself it's not that bad, but at the same time, if we ever want to insert a full form advancement, it ignores the data of the full form and still tries to look it up in the corresponding unit type.

The logic of the code is to fetch the advancement in the unit type when they are spelt in the short form, as 
```
[advancement]
id=useful_compressed_advancement_id
[/advancement]```

So can we trigger ``get_type_advancement`` only if we find a short-form advancement? And if the advancement is in the full form and includes everything, we use that information and don't call ``get_type_advancement``. As no advancements are in the short form right now, it will still be useless. But even if the space-saving plan will be completed, I don't see any logic in stripping the full data if any advancement happens to provide it.

**Comment by Discontinuum** [comment]
About hacks, I often have to use at least temporary hacks because usually I want my mod to work with the current stable

**Comment by Dugy** [comment]
Sorry that it took me so long to realise what you were trying to do and what's the actual problem there.

The reason why the thing you're suggesting can't be done easily is that these advancements depend on some of the unit's properties, and are thus different for every unit type. This is because some advancements add spells that need animations when cast, and the macro that adds the advancements to the unit types takes some animation frames as arguments.

The only way around this I can think of is to write some code that will scrape the unit type for something that looks like a casting animation, or at least something that could be used as one, and replace some placeholders in the advancement code dynamically. That way, the shared advancements could be moved out of the unit code and added via `effect=add_advancement` just before advancing and clean up the mess that LotI has with advancing.

**Comment by Discontinuum** [comment]
>  This is because some advancements add spells that need animations when cast

For my mod that is not that much of a problem, I was going to give up on animations, missile animations are enough for me. I know you care a lot about animations but my friends tell me that better to have playable units without animations than no playable units. Still the way advancements data are ignored creates troubles.

> The only way around this I can think of is to write some code that will scrape the unit type for something that looks like a casting animation

We can store frames in a variable. That might be ugly though, as code filling the variable will be probably in another place than units themselves

**Comment by Dugy** [comment]
> For my mod that is not that much of a problem, I was going to give up on animations, missile animations are enough for me.

That does not matter, it is written in a way that it requires animations. You can set some defend animation for that if you don't have anything better, but you can't do it without an animation because the macro is written in a way that it contains unit frames. It's difficult to write the code in a way that would support both.

> We can store frames in a variable. That might be ugly though, as code filling the variable will be probably in another place than units themselves

You would need to turn the macro into something that lua can work with.

**Comment by edwardspec** [comment]
> Hm, I see that this mode of operation was deliberately introduced in this commit for "effects" [863a498](https://github.com/Dugy/Legend_of_the_Invincibles/commit/863a49884b5e81fcca5583693b96d075f209d39c) (and later "effect_containers" was coded by analogy). The description exactly says that "the idea is to remove full [advancement] tags from the units at some point in the future". But 4 years passed and this future didn't come. Should we still stick to it?

See https://github.com/Dugy/Legend_of_the_Invincibles/blob/unitdata-lua/lua/unitdata1.lua for what was the idea (this implementation has significantly better performance than WML-based `unitdata.lua`).

It was blocked on the need to rewrite redeem in Lua first (like in #561).

**Comment by Discontinuum** [comment]
Is it necessary though to ignore an advancement's data if it happened to be in the full form? Ofc if you're planning that advancements be regularly in the form "{id = adv_id}", you need a way to extract their values from the unit type. But doing so always is like burning bridges (we form the short advancement and nothing else ever). Maybe that was just missed from consideration

**Comment by edwardspec** [comment]
Feel free to change this. Please thoroughly test that it doesn't break anything.

Lua-based storage doesn't use this code, so if it's used at some point in the future, it won't be affected by this change. It also uses `get_type_advancement()` in https://github.com/Dugy/Legend_of_the_Invincibles/blob/0e6129bfd7f63f2ee52324e87fdd65aaa562161e/lua/unitdata1.lua#L148-L153
