### ISSUE TITLE
Need assistance with MP safe lua GUI for traders

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#614]
Working on a new lua based gui for interacting with traders.  I've just about got it (mostly by stealing from redeem_menu), but I know there's stuff you need to watch out for so as not to break MP.  And that is the extent of my knowledge of MP right there.

Also, the first time you visit the trader and buy one or more objects, the actions that occur don't happen in the order I (think I) coded them.  I THINK this might be in [item_pick_menu], called when I fire item_pick.  I think it might be deferring the actions in some way I don't understand.  But, this only seems to happen the first time.  I don't get it.

I'd appreciate some assistance here.  Mostly with the MP and out of order stuff.  [Being able to change the text of the "Nothing" button would be nice, too. EDIT never mind, I added a use_markup to menu_items].  And of course, any feedback in general is most welcome.

Code and test material at #613

**Comment by Dugy** [comment]
You can fix the desynch issues by doing all the GUI stuff inside a function that is called through `wesnoth.synchronize_choice`, with no side effects, and use the results to make the changes you wanted.

Example how to use that:
```lua
function choose_items()
  local bought = []
  -- Use a GUI to fill up the array
  return bought
end

local bought = wesnoth.synchronize_choice(choose_items)

for i in 1,#bought do
  gold = gold - bought[i].cost
 put_item_on_ground(bought[i])
end
```

**Comment by white-haired-uncle** [comment]
Okay, that should help once I get my head around it a bit.

In your example, you don't decrement gold until after you're done buying, which could lead to being able to buy things you can't afford.  I assume you're just ignoring that detail and the assumption is a local gold count will be used inside choose_items().  But, this brings up a question, should I NOT be touching the global gold value (see [store_gold]) inside choose_items?

What about gems?  The option says "Buy a ruby (currently having rubies of them)", where rubies is a global wml variable.  Do I need to use a local rubies to keep that correct inside choose_items, and then deal with the global one after return?

Currently, after choosing an item, choose_items just calls itself to continue.  Maybe not the way I'd do it from scratch, but I'm copying a lot of code here, and that's how redeem_menu did it.  If I wrap my first call to choose_items in wesnoth.synchronize_choice, does that also protect any other functions called within, including recursion?  Or should I use wesnoth.synchronize_choice on every function call inside the gui part?

While I'm thinking about it, is this bad? ` local gold = wesnoth.sides.get(1).gold` because it assumes side 1, so I need to find a way to get "side.current"?

**Comment by white-haired-uncle** [comment]
I'm not having much luck finding documentation, or examples, for wesnoth.synchronize_choice.

I did get pretty much everything else fixed, and moved the gold, item_pick, etc stuff out of the gui code more or less per your example.

`local bought_items=trader_menu(newcfg)`   Works fine now (as far as I can tell of course)

`local bought_items=wesnoth.synchronize_choice(trader_menu(newcfg))`   lua/core/_initial.lua:50: bad argument #1 to 'elem' (expected a function)

`local bought_items=wesnoth.synchronize_choice(trader_menu)`  doesn't blow up immediately, but w/o the proper arguments it's not going to do much.

And, "wesnoth.synchronize_choice has been deprecated indefinitely.;  (Note: You should use wesnoth.sync.evaluate_single instead in new code)"

**Comment by Dugy** [comment]
> In your example, you don't decrement gold until after you're done buying, which could lead to being able to buy things you can't afford.

You have to keep some local copy of the gold to check what is affordable until the shopping is finished. Same for gem quantities if you want to show the count of owned gems.

> If I wrap my first call to choose_items in wesnoth.synchronize_choice, does that also protect any other functions called within, including recursion? 

Yes, if you use recursion, the functions inside will also be synchronised as long as they don't change anything outside of their scopes that would be used later.

> While I'm thinking about it, is this bad?  local gold = wesnoth.sides.get(1).gold because it assumes side 1, so I need to find a way to get "side.current"?

Yes. I think that there is something in the Lua API to get the current side number. If there isn't, you can load the WML variable from lua.

> `local bought_items=wesnoth.synchronize_choice(trader_menu)` doesn't blow up immediately, but w/o the proper arguments it's not going to do much.

This is how you have to do it. You need to pass it a function as argument, and it will call the function in a special way that it will be executed only by the current side and the result will be sent to all the others (thus, hypothetically, a cheater in multiplayer could change the code to allow himself to buy stuff for cheap, so some validation of the returned value has to be done).

Your problem is that you can't pass it an argument. This is not a big limitation, because the lua function can have a closure, using variables defined in the context around it.

Example:
```lua
local newcfg = cfg -- I don't remember what exactly is here, you'll probably initialise it differently
function trader_menu_no_arg()
  trader_menu(newcfg)
end
local bought_items = wesnoth.synchronize_choice(trader_menu_no_arg)
```

**Comment by white-haired-uncle** [comment]
That's.  Interesting. I think I can work with it.

But I think I'm kind of missing the point.  The more I think about this the more confused I get.  One example I read had a player changing an attack (say by equipping an item?) without another player having the same info, and then if combat occurred you could have a unit that is alive or dead, depending on who you ask.  I can really only understand this if in MP player turns are concurrent.  And if this is a problem, why only in lua?  I guess WML has some MP-safety built in but lua doesn't?

But, accepting for the moment that there are things that need to be in sync.  Looking at your original example, it looks like choose_items() is just populating an array, which seems pretty innocuous.  Dropping an item on the ground is something I can accept would need to be coordinated between players.  But that part has been taken out of the stuff run inside wesnoth.synchronize_choice.  It all seems backwards to me.

Which is a long winded way of saying that, in the recent example you posted, I have no idea what stuff would need to be within trader_menu_no_arg(), and what could be outside.

The only thing I can think of that I'm doing in there which might be dangerous is setting a global wml var trader_buys.unique_trader_id.item_number=yes so the trader.  But is that really global, or just global for my side?  What about variables like rubies, is that actually something like side[1].rubies but I never see that because I'm always side 1?

I'm pretty much lost at this point, if that's not clear by now.

**Comment by white-haired-uncle** [comment]
Is that 

 return trader_menu(newcfg)

**Comment by Dugy** [comment]
I will try to explain it from the basics.

Everything that happens is done by all clients in MP, and is replicated when going through a replay. Thus, any time an event is triggered, the code inside that event should go exactly the same way every time, otherwise you' risk getting into a situation that seems impossible to the other client (or replay) and trigger a desync error.

Of course, some actions that trigger the events have to be sent from the player who makes them to the others, otherwise the events would not be triggered at all in the other client. These are of course things you do through the game's built-in GUI, such as moving, attacking, ending a turn, selecting a menu item etc. If you have a `[message]` that is shown only to one player, his choice is sent to the others. As a consequence, most control done via WML does not cause desync.

However, there are things that can happen without having an effect on the game state, and they will cause desync if some code changes the game state according to them, regardless if they're done in WML or lua. An easy trap is an event occurring when selecting a unit (that is not sent to other players). Another problem is doing something accordingly to a global variable, each player has different global variables and the outcome of the access will be different for each player. Another thing is the lua-based GUI.

By default, a lua-based GUI shows to each player, and if they don't do the same thing there, there will be desync. To prevent that from happening, you have to call it from within a function that is called via `wesnoth.synchronize_choice`. Anything done inside a function called that way will be run only by the player whose turn it is, and the result of the function will be sent to each player, and the execution will resume for each of them from that point. Therefore, the result of that function can depend on anything, a player's choices, presence of other installed add-ons, previous clicks on units, global variables, because only that one player is executing it. This also means that any changes to game state inside this function will cause desync, because this code was run only by the current player.

The last piece of code you've pasted is incorrect, because some of the code executed by the GUI has side effects which will affect only the gamestate of the player whose turn is it. _Any_ changes to gamestate done from inside `gui_show_dialog_no_args` will thus cause desync. Anything that was set inside that GUI can only change the return value of the function, because that one alone is propagated to other players.

That is why you can do it only by building an array of items the player has bought (done only by the current player if inside `synchronize_choice`), return it through `synchronize_choice` (this passes the value to every other player) and apply the changes afterwards (this is done by all players in the same way because they got the same result from `synchronize_choice`).

**Comment by white-haired-uncle** [comment]
That is a very good introduction to the subject, and something that is sorely missing from the wiki "documentation" (which I find much like reading one of those choose your own adventure books with most of the pages torn out).

But I still don't understand why, when I try to wrap the whole thing, it complains that it doesn't like "part" of a table and is stripping some stuff out, leaving me with an empty list of items returned.  Given that I don't really understand the issue, don't have access to decent documentation, and could only "fix" (as it, make it stop giving errors) the problem by making random changes, I think I'm done.  I like what I've come up with (mostly), and I learned a good bit, but if it is to survive someone who knows what they're doing will have to tackle the MP garbage.

Or we could just arrange a little accident for the two or three people that play MP and/or care about replays.  Just tell me they're the ones that invented wiki and I'll be happy to fix the glitch as they say.

**Comment by white-haired-uncle** [comment]
There's some ugliness here.  A few things that just don't make sense to me.  But I think it might be not entirely unlike your first example (though I had no luck with wesnoth.synchronize_choice).

```
function wesnoth.wml_actions.trader_menu(cfg)
        local newcfg={}
        for index, value in pairs(cfg) do
                newcfg[index] = value
        end
        local side_number = wml.variables.side_number
        local gold = wesnoth.sides.get(side_number).gold
        newcfg.gold=gold

        local bought_items = wesnoth.sync.evaluate_single(
                function()
                local stuff=trader_menu(newcfg)
                return { value=stuff }
                end
        )
        local items={}
        for _,list in pairs(bought_items) do
                if(type(list) == "number") then table.insert(items,list) end  -- one item returned
                if(type(list) == "string") then                               -- multiple items returned
                        for w in string.gmatch(list, "[%d]+") do table.insert(items,tonumber(w)) end
                end
        end
        for _,item_num in pairs(items) do
                local item=loti.item.type[item_num]
                wml.fire("gold",{side=side_number,amount=-item.cost})
                loti.item.on_the_ground.add(item.number, cfg.x, cfg.y, item.sort)
                wesnoth.wml_actions.fire_event{ name="item_pick", { "primary_unit", { x=cfg.x, y=cfg.y } } }
        end
end

```

**Comment by Dugy** [comment]
> But I still don't understand why, when I try to wrap the whole thing, it complains that it doesn't like "part" of a table and is stripping some stuff out, leaving me with an empty list of items returned. 

It is actually written in the documentation, but it's a bit hard to notice.

The problem is that you have to return a WML table, which is a specific subset of lua tables. These are lua tables that can be converted into WML variables or code (which is necessary here because the message to synchronise the result encodes it in WML).

It has to have a structure like this:
```lua
local usable_table = {
  something = 12,
  something_else = "a value",
  {
    "would_be_the_name_of_the_tag"
    {
      somethig_inside_that_tag = 12
    }
  },
  {
    "would_be_the_name_of_another_tag"
    {
      somethig_inside_this_tag = "stuff"
    }
  }
}
```

If you call `wesnoth.dbms` on a variable, it will display it and also tell you if it's a WML table or not, and in case it isn't, it will explain why.
