### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#63]
Hi 

I attach the log of my long "debugging" session . ( i jsut filtered the 3 most frequent lines with warnings)

[20171230.log-3.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594504/20171230.log-3.txt)

This is the part at the same time as the image

`20171229 16:48:18 warning unit: Unknown attribute 'animate' discarded.
20171229 16:49:28 warning unit: Unknown attribute 'animate' discarded.
ERROR: TYPE ERROR: expected string but found null (null())
  enemy_of
  unit_at
  direction_from
formula type error: TYPE ERROR: expected string but found null (null())
ERROR: TYPE ERROR: expected string but found null (null())
  enemy_of
  unit_at
  direction_from
formula type error: TYPE ERROR: expected string but found null (null())
20171229 16:52:18 error scripting/lua: ai/micro_ais/cas/ca_fast_attack_utils.lua:178: bad argument #1 to '__index' (unknown unit)
stack traceback:
        [C]: in metamethod '__index'
        ai/micro_ais/cas/ca_fast_attack_utils.lua:178: in field 'get_unit_info'
        ai/micro_ais/cas/ca_fast_combat.lua:82: in function <ai/micro_ais/cas/ca_fast_combat.lua:8>
        (...tail calls...)
20171229 16:52:18 error scripting/lua: ai/micro_ais/cas/ca_fast_attack_utils.lua:178: bad argument #1 to '__index' (unknown unit)
stack traceback:
        [C]: in metamethod '__index'
        ai/micro_ais/cas/ca_fast_attack_utils.lua:178: in field 'get_unit_info'
        ai/micro_ais/cas/ca_fast_combat.lua:82: in function <ai/micro_ais/cas/ca_fast_combat.lua:8>
        (...tail calls...)
20171229 16:52:18 error scripting/lua: ai/micro_ais/cas/ca_fast_attack_utils.lua:178: bad argument #1 to '__index' (unknown unit)
stack traceback:
        [C]: in metamethod '__index'
        ai/micro_ais/cas/ca_fast_attack_utils.lua:178: in field 'get_unit_info'
        ai/micro_ais/cas/ca_fast_combat.lua:82: in function <ai/micro_ais/cas/ca_fast_combat.lua:8>
        (...tail calls...)
20171229 17:11:19 error general: Unknown key: page up
20171229 17:11:19 error general: Unknown key: page down
20171229 17:11:31 warning engine: attempt to filter attack for an event with no attack data.

20171229 17:11:31 error engine: failed to auto-store $second_unit at (20,21)

`

![lua_error_2017-12-29_16-52-34](https://user-images.githubusercontent.com/31039036/34455253-78818876-ed7b-11e7-92b4-f7b0ef4fad6c.png)

[LotI1-The_Beginning_Tour_8-lua-error-just-hapened.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594492/LotI1-The_Beginning_Tour_8-lua-error-just-hapened.gz)

[LotI1-The_Beginning_Tour_8.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594493/LotI1-The_Beginning_Tour_8.gz)

[LotI1-The_Beginning-Sauvegarde_automatique9.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1594494/LotI1-The_Beginning-Sauvegarde_automatique9.gz)

**Comment by Dugy** [comment]
This is not a LotI error. It's just a bug in a Wesnoth feature that's used heavily in LotI but rarely elsewhere. Please report it to Wesnoth developers.

**Comment by matsjoyce** [comment]
@mattsc Have you got this one?

**Comment by mattsc** [comment]
Thanks for the ping, @matsjoyce 

There are two different things in this log.  The type errors at the beginning are a know open bug:
https://github.com/wesnoth/wesnoth/issues/2247

The Lua error is something I should be able to take care of.   However, I cannot reproduce it.  I took the LotI1-The_Beginning_Tour_8.gz file and let it play through the AI turns from there several times, but no Lua error.  (I also did so with the two other files, although I didn't think those were relevant.  I need something from before the error happens.)  So it's either only occurring under very specific circumstances or I am doing something wrong.  Any pointers?

And just for the record, I did get the type errors, so they are not a pre-requestie for the Lua error to happen.

**Comment by matsjoyce** [comment]
@alain-bkr Are you using the latest version of wesnoth (very recent git)?

**Comment by mattsc** [comment]
Just FYI, I used the very latest version of Wesnoth master, compiled this morning.  However, the line in the Micro AI throwing the error has not been touched in ages.  So unless there was an underlying error in Wesnoth causing Lua to misbehave, the exact version should not matter; as long as it is relatively recent.

My guess is that it is something that only happens for very specific "constellations" of units on the map, or sequences of moves/attacks/units dying/etc. (otherwise we would have already discovered it), so a way to reproduce it is crucial.

**Comment by arobinson** [comment]
Just had this happen with the latest LotI and Wesnoth 1.12.6 on a Mac. Seems to happen after ending turn 8. I also provided the auto save from turn 9 after the error. It could be the Exterminator, but not sure. 
![screen shot 2018-02-09 at 9 14 02 am](https://user-images.githubusercontent.com/93213/36037530-455ceaca-0d7a-11e8-9de4-d061643e9792.png)

[LotI2-The_Chase_Turn_8.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1711651/LotI2-The_Chase_Turn_8.gz)

[LotI2-The_Chase-Auto-Save9.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1711644/LotI2-The_Chase-Auto-Save9.gz)

**Comment by mattsc** [comment]
Okay, I finally managed to reproduce this error (albeit on Turn 9, not 8).  I'll look into it.

**Comment by mattsc** [comment]
The error is indeed due to the Exterminator killing a unit, but specifically a unit _other than the attacking AI unit_.  And even then it only happened sometimes, so that's why we had not encountered it before.

I fixed this in mainline for 1.13 [here](https://github.com/wesnoth/wesnoth/commit/85b46f34b066580aab1e8fb3b6e9ea7ba108ad8c).

For 1.12, you have to do this in the local file in LotI.  Note that the **data variable syntax is different** for 1.12 and 1.13.  It's `self.data` in 1.12 and simply `data` in 1.13, so you need to take that into account when making the changes.  The easiest is to just locally move the two lines that get moved into the if statement, rather than copying them from the link.
