### ISSUE TITLE
ash_cooldown

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#630]
The phoenix ashes potion produces errors in the current `master` version

```
[unstore_unit]: variable 'ash_cooldown[]' doesn't exist
```

[LotI2-The Den of Evil Turn 12.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/12211236/LotI2-The.Den.of.Evil.Turn.12.gz)

**Comment by Discontinuum** [comment]
Looked at the code, seems it's this commit https://github.com/Dugy/Legend_of_the_Invincibles/commit/41ab85c3bf715b85f6ab1d764198740d8b3506ab replaced the old ``FOREACH`` macro with the index variable ``h`` to a new ``[foreach]`` forgetting to set the index variable name (or change it to default ``i``)

**Comment by Dugy** [comment]
I was using random letters for iterators because events fired inside of other events' iteration had conflicts with variable names. I should have warned @white-haired-uncle about this when he was making changes to these foreach blocks. Either way, I think this variable name aliasing is no longer an issue with the new WML syntax unless they're nested in the same event, so naming the indexes like in any normal programming language should be fine.
