### ISSUE TITLE
Resistances not applied as quoted

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#649]
The "Mystic Occult Armour of Carpathia" shows a 30% resistances to physical damage, but only 13% is getting applied when I check the unit. In the attached save game, find the Ancient Lich "Gleraeran" at the bottom left of the map in the fortress. Hover over his HP and you will see a impact resistance of 15%. Now drop his armor to the ground. His impact is now 2%, a difference of 13%, not 30%. 

Am I missing something and this not additive or is this a bug in the armor or in the display?

[LotI2-Avengers Turn 8.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/12614306/LotI2-Avengers.Turn.8.gz)

**Comment by Dugy** [comment]
That is intended to avoid stacking too much resistance. There are two rules that cause this:
* The number you see is not added to the current resistance, it reduces the damage taken without it by the percentage; thus, if a unit has 50% resistance and takes an armour with 30% resistance, the resulting resistance becomes 65% (30% less damage taken than if it had 50% resistance)
* The resistance improvement of impact damage is halved, so that a dwarf with lots of armour would not be super resistant to all physical damage; I chose impact because hammers are good at breaking through armour
