### ISSUE TITLE
no victory 

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#66]
I moved Lethalia to the south border of the map, and did not got victory

I had to move Efraim 
[LotI1-Infinite_Legion_Tour_31-no-victory.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/1608674/LotI1-Infinite_Legion_Tour_31-no-victory.gz)

![victory_not_reached__while_lethalia_at_southern_border_2018-01-06_00-40-33](https://user-images.githubusercontent.com/31039036/34638674-37b62454-f2d1-11e7-803a-5bab4273a7c6.png)

**Comment by Dugy** [comment]
That is a consequence of the earlier bug you encountered that prevented Lethalia from changing type. The exact victory condition is that the southmost two rows of hexes must be visited by a unit that can recruit, and since Lethalia erroneously isn't able to recruit, she cannot trigger the victory condition.

**Comment by alain-bkr** [comment]
I did not noticed  Lethalia could not recruit , it thougth it was a feature.

why close this bug, it is real one, and it don't see which openbug is taking this into account

**Comment by Dugy** [comment]
Bug #62. She should have obtained her recruitment ability and appearance at that time.

**Comment by alain-bkr** [comment]
oh ! 
thanks for enlightment !
