### ISSUE TITLE
Firecast with Violent mage items does not work with fire dragon legacy

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#688]
[FirecastBug.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14529972/FirecastBug.gz)

Vamal in this same game has all 3 violent items. I checked the unit information and it does show firecast. Neither attacking with axe or with the violent beatdown triggers firerast

**Comment by Dugy** [comment]
The problem is that firecast has an explicit list of fire attacks that it automatically activates. `fire breath` is on the list, but `fire breath legacy`, the one added by Fire Dragon Legacy, isn't. That's an easy fix.

With the fix, you need to proceed into the next scenario and modify the unit's inventory.
