### ISSUE TITLE
frail tide / conviction not included in unit info penetrates table

### ISSUE THREAD

**Issue by white-haired-uncle** [Dugy/Legend_of_the_Invincibles#691]
In Unit Information, the description for frail tide and conviction are shown (and the abilities do work) but the resistance/penetrates table does not include the penetrates.  It looks like unit info looks for resistances with id=fire_penetrates (for example), which is what most items/amlas seem to set.  

I'm wondering if frail/conviction are the only things that affect multiple (physical, non-physical) resistances.  Only ones I can think of.  EDIT: nope, dark dragon legacy.

Also, it looks like the report just uses the last [resistance] sub it finds for an attack type.  What if there are more than one (could there be)?  How does bfw handle that during combat?  [Note to self: And is it always the same, or is this finally a clue to why I can get such great cold penetration with my CMs???]

**Comment by white-haired-uncle** [comment]
Turn the effect on/off at the beginning/end of an attack?

**Comment by Dugy** [comment]
No need, I have figured out a better way of doing it, it's even included in the damage calculation.

**Comment by Dugy** [comment]
Okay, I have changed how penetrate works in commit 5dcc500.

**Comment by white-haired-uncle** [comment]
That sort of works.

Efraim's cold penetration from legacy still affects Lethalia's blizzard attack (and the target stats) on the flies.

The Gryphon Rider's arcane penetration from Void armour still affects Lethalia's fairie fire (and the target stats) on the flies, unless you drop the item to the ground and pick it up in which case it seems to work as intended.

I'm guessing it would work for specials earned by legacy and other means, but only for new instances?

I think I like this, but I also think it's still confusing.  Even if a new field was added to the res/pen table to reflect ability based "penetration", still need to explain to the user why they are different in a clear way.

[LotI2-Infernal Narrows-Auto-Save3.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14546889/LotI2-Infernal.Narrows-Auto-Save3.gz)

**Comment by Dugy** [comment]
Yes, you need to cause the unit's properties to be updated somehow. Changing something in the inventory is the easiest way of doing that on purpose (you can change it back right afterwards). If this wasn't a lua-only change, you would have to start a new scenario and update the properties later, but it's not necessary in this case.

**Comment by white-haired-uncle** [comment]
Seems like there should be a global variable for loti-version.  That way, each save would contain its version.  A global preload event would be aware of the current version (or perhaps just the most recent version that requires old saves to be updated), call a handler accessing an array of upgrade functions each tagged with the current version at its time of creation.  A save gets loaded, any/all backward compatiblity issues are addressed, loti-version is set to current, and any subsequent saves will be tagged with the current version to show they are up to date at point current.

Or something like that.

**Comment by Dugy** [comment]
It is definitely doable, but it feels like too much effort for too little value.

First, I don't upload updates so often, so it's generally fine if the update arrives over the course of a scenario or two. It would not seem strange to you if they change appeared over the course of several scenarios if you weren't expecting it to be fixed as soon as you updated.

Second, it's impossible to remember to change a version number somewhere after every gameplay affecting change. I think that a git hook to do it automatically would be possible, but it would result in a load of merge conflicts.

Third, it would not even remove all counter-intuitive behaviour, because some things are snapshotted in mid-scenario saves, and only finishing the scenario will update it.

**Comment by Discontinuum** [comment]
So you won't be able to debuff enemies by resistance penetrating units now to attack with a different unit?

**Comment by Dugy** [comment]
No, only conviction and frail tide will do that now.

**Comment by Discontinuum** [comment]
Some items now become useless, for example

Eternity's End – mace
Sets damage type to arcane
Enemy resistances to blade decreased by 20%

**Comment by white-haired-uncle** [comment]
Give that to a highwayman before advancing to shadow prince, along with rationality gloves.

**Comment by Dugy** [comment]
These items could be changed, modifying damage types with The Unprecious Ring or Rationality is supposed to be an option, but I'd prefer if there was some more immediate use of it. There is already a weapon with suck that deals a damage incompatible with suck, there is no need to have more items requiring switching the damage back to get to their full potential. If there was a unit with a mace that also had blade damage, it would be another thing, but I don't think there is.

So, maybe Eternity's End could get frail tide instead of the blade resistance reduction?

**Comment by white-haired-uncle** [comment]
There should be some things that require a little juggling to make use of.  It keeps things interesting.  Otherwise you're just running around collecting stuff.  The discovery is at least half the fun.

**Comment by Dugy** [comment]
So I can close this issue, I assume.

**Comment by white-haired-uncle** [comment]
BTW, I think this makes Prophet and Celestial Messenger even more unbalanced relative to your other units.  Making penetration unit-specific really enhances the relative value of frail tide / conviction.

These two units already needed taking down a notch.  I wouldn't mind stripping them of frail tide / conviction for starters.

Also increases the value of Legion Slayer / Hunter of Kings.  They now seem very powerful (+2MP, penetrates, ft/convic, decent resistances) for a two item combination.  Perhaps a third item that is needed to unlock frail tide?  I'm thinking a book, since that requires a commitment.

**Comment by Dugy** [comment]
I was thinking that maybe the existing effects of Frail Tide and Conviction could be made weaker. Or the penetrations could be made stronger. That would be an easy solution.

Of course, adding more requirements is a more creative approach.
