### ISSUE TITLE
Error after pulling latest -- picking up object

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#718]
I just pulled the latest from github, and am now getting an error picking anything up

Is this a bug or is this due to using an existing save game with the latest code?

<img width="1050" alt="image" src="https://github.com/Dugy/Legend_of_the_Invincibles/assets/93213/0cb09d38-b8a7-452c-abd4-ea0dba9879a0">

Save game: 
[LotI2-Tundra-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14767012/LotI2-Tundra-Auto-Save1.gz)

Also got an error from the initial load of the save game of
```
loti.item.type[371]: not found in item_list
```

Save game:
[LotI2-Tundra 8.34.35 PM.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14767015/LotI2-Tundra.8.34.35.PM.gz)

**Comment by Dugy** [comment]
Item number 371 was added very recently, so it could be some minor incompatibility. However, I expect this to happen when using a newer save file with older version of the add-on rather than the other way around.

**Comment by white-haired-uncle** [comment]
In [LotI2-Tundra-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14767012/LotI2-Tundra-Auto-Save1.gz) there's a menu item "Help on advancement tree".  Where is that from?

**Comment by white-haired-uncle** [comment]
I don't see any issue with Auto-Save1.

I do with the start of scenario file.  I get the message about item 371.  Also, when I look at the Elf Overlord's Hunter of Kings I don't see the dependency on item 371.  But I can drop items and pick them up, etc.  -- Check that, I did get that popup error trying to pick up a gem.

testing with 1.16.10 BTW

**Comment by Dugy** [comment]
What happens if you load a scenario start rather than a mid-scenario save file? As a result of having rewritten a lot of information into lua, information gets snapshotted into the scenario, some doesn't, and they can get messed up if you change revision mid-scenario.

**Comment by white-haired-uncle** [comment]
It's the start of scenario file that's showing me the issues.

**Comment by arobinson** [comment]
> In [LotI2-Tundra-Auto-Save1.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14767012/LotI2-Tundra-Auto-Save1.gz) there's a menu item "Help on advancement tree". Where is that from?

Custom plugin I wrote for providing more information about LotI adavancements :)

**Comment by white-haired-uncle** [comment]
item_list does not contain the new item in the scenario start file.  But if I look at inspect, it does during turn 1.  I don't know what the wesnoth startup process looks like, but it  seems like loti.item.type is getting populated before {GENERATE_ITEM_LIST} reads in the new info?

**Comment by Dugy** [comment]
I have changed the code to read the data from the unit type, which is not stored inside the scenario and is always up to date.

**Comment by white-haired-uncle** [comment]
That takes care of one of the issues.   I'm still getting errors picking up gems.

**Comment by Dugy** [comment]
Can you upload a save file where that can be replicated quickly?

**Comment by white-haired-uncle** [comment]
Working on it.  But first a "question":

I'm learning about metatables and I'm a bit confused here.

At the beginning of the scenario, GENERATE_ITEM_LIST replaces item_list with the contents of item_list.cfg, then creates descriptions using [describe_all_objects] and then clears loti.item.type_cache. I can see the descriptions are being correctly populated in item_list.

Then in item_pick, gui.show_popup accesses say loti.item.type[527] which does not exist, so it calls loti.item.type_index which calls loti.item.type_load which checks the (empty) cache and calls loti.item.type_reload which (now) populates the cache from the data loader unit type (which does NOT contain a obj.description for things like gems) and returns cache[527].

Then gui.show_popup fails as loti.item.type[527].description (or flavour) is nil.

So, since item_list seems to no longer be used here, unless someone calls loti.item.describe_item I fail to see how the description won't be nil.

I also don't understand why it was broke before you made your change, but that's just one more thing on the long list of things I don't understand and will never get around to.

P.S.  I only see a couple of uses of item_list in WML.  Might it be approaching time for it to go away?  I know I'm getting confused having two copies of what is essentially, but not guaranteed to be, the same data.  I don't really care, this is just an academic question.

**Comment by white-haired-uncle** [comment]
One tile north of Lethalia

[LotI2-Tundra-pick-up-57.76.gz](https://github.com/Dugy/Legend_of_the_Invincibles/files/14791030/LotI2-Tundra-pick-up-57.76.gz)

**Comment by Dugy** [comment]
I don't understand lua metatables good enough to be able to answer your questions. One thing I can tell is that the data is sometimes accessed as `loti.item.type._load()`, which might imply it's not loaded implicitly when first used.

The problem that was happening was that only the WML list of items had generated descriptions, the lua metatable didn't have these descriptions. There was a bit of a chicken and egg problem, because the descriptions themselves need the metatable to be ready in order to describe dependencies of set items.

Anyway, I fixed it.

> Could these simply be replaced with [loti_item_type] ?

Probably. I don't remember where are they still used. If this was C++, I'd just remove it and correct the parts that fail to compile, but it's not so easy here.

**Comment by white-haired-uncle** [comment]
__index is called automatically when a missing field is accessed, which I assume happens the first time you access anything, which calls load.

https://www.lua.org/pil/13.4.1.html

> Anyway, I fixed it.

Ugh. I didn't think to set the cache before (and after) calling describe (stack overflow as type called describe which called type...).  Darn simple now that I see it.

I'm going to take a shot at getting rid of the wml array.

**Comment by arobinson** [comment]
Thank you for the fix, both issues have not reproduced again

**Comment by Dugy** [comment]
> Ugh. I didn't think to set the cache before (and after) calling describe (stack overflow as type called describe which called type...). Darn simple now that I see it.

That part seemed obvious to me. I ended up doing a bit of trial and error with writing the descriptions into the metatable.

> I'm going to take a shot at getting rid of the wml array.

Thanks.

**Comment by white-haired-uncle** [comment]
Ran into a minor issue that needs some consideration.  Almost nothing touches item_list at the moment, so this may not matter much. How to handle loti.item.type[57], since there is no item 57.  Currently it throws an error.

Consider test_scenario's turn refresh.  It seems to just blindly look at all items from 1-372 and add them to storage.  I don't know how it deals with the missing item, the code kind of hurts to look at.

If we replace it with:

```
                [loti_item_type]
                    number=$i
                    to_variable=item_info
                [/loti_item_type]
                {INSERT_INTO_ITEMS $item_info.sort $i}

```

it works fine until it hits i=57.

Two thoughts come to mind:  

1. Have loti.item.type return nil instead of an error and expect the receiver to deal with it.
2. Have loti.item.type take number=*, or create a new tag, which returns a table of all valid items and iterate over that.

I kind of like 2, since that way you don't have to update this event (for example) every time you add an item.  However, I know there are items>372 and for some reason I don't know this event doesn't seem to be interested in the rest.

**Comment by Dugy** [comment]
> Consider test_scenario's turn refresh. It seems to just blindly look at all items from 1-372 and add them to storage. I don't know how it deals with the missing item, the code kind of hurts to look at.

WML is more tolerant than lua to these kinds of mistakes. It's because most of the tags are written in C++ and since C++ is statically typed, every type is converted into the correct type somehow, creating placeholder values for nearly everything that is incorrect.

> Two thoughts come to mind:

Why don't we just create item 57? It's a mistake there's no such item in the first place.

> I kind of like 2, since that way you don't have to update this event (for example) every time you add an item.

There is no way an item could be added without loading a safe file, which reloads the lua environment.

**Comment by white-haired-uncle** [comment]
Could add a 57 I suppose.  Maybe something dark?  I've just about given up trying to advance a chaotic faction to my army (save maybe in ch 10) because everything is so slanted toward lawful.  I still like the idea of a tie-in with one of the spinoffs.

As far as updating the event I mean you had to update test_scenario to use 371 instead of 370 when two new items were added.  I didn't even know that would need to be done.

Having something return a table of all valid items, even with new ones and accounting for any "holes" just seems more robust.  But from the looks of it, it's only test_scenario, Jungle Hell, and two multiplayer which touch item_list, and I'm pretty sure the mp ones don't need to so it may not be worth much thought.

**Comment by Dugy** [comment]
> Could add a 57 I suppose. Maybe something dark? I've just about given up trying to advance a chaotic faction to my army (save maybe in ch 10) because everything is so slanted toward lawful. I still like the idea of a tie-in with one of the spinoffs.

If have in mind something that you've been sorely missing, feel free to create something. But be prepared that I will review it.

> As far as updating the event I mean you had to update test_scenario to use 371 instead of 370 when two new items were added. I didn't even know that would need to be done.

It doesn't need to be done, it's just useful to test the item.

> Having something return a table of all valid items, even with new ones and accounting for any "holes" just seems more robust.

Lua has a function to iterate through all elements in an array, skipping all nils in the way. Also, there is a table with all droppable items with no blanks, which is used for choosing what item will drop from a unit.
