### ISSUE TITLE
Incinerate cannot be cured by a healer

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#75]
When a unit has been incinerated the icon on the screen for the fire shows: "in flames: This unit is in flames. It will lose 16 HP per turn, unless cured by a healer or by standing on a village".

A healer will prevent the damage and the village will cure the burning, but a healer will not cure the burning (only villages work). Still seen with the latest code from github as well as what is published to the wesnoth add-on server

**Comment by Dugy** [comment]
There is an old bug that only the default healing works (the one that heals 8 hp per turn). I am afraid to upload a fix because I am worried that it would cause unexpected consequences.

If you want to help, please edit file utils/abilities.cfg, find this line:
`id=healing_other`
and replace it with:
`id=healing`
If it won't break anything, I will publish that fix. It _will_ cause temporary oddities.

**Comment by arobinson** [comment]
That did fix it. I also went through my save file and replaced all the id="healing_other" with id="healing" so as to retroactively apply the change.

**Comment by Dugy** [comment]
In theory, you should encounter no bugs now. Please report how will it go.

**Comment by alain-bkr** [comment]
I guess it is the same thing for fool's potion , not being neutralized by elvish healer (+16) ( cf #60 )  ?

**Comment by Dugy** [comment]
Yes.
