### ISSUE TITLE
segfault during opponent's turn

### ISSUE THREAD

**Issue by alain-bkr** [Dugy/Legend_of_the_Invincibles#80]
I upgraded wesnoth engine and got (from 0bc03e14c749699b7dfee mid-february) to current ( 11d48f16390266 ,march 9th)

There is a segfault very quickly, very often at the first turn.

I attached the backtrace in gdb.

[20180309.segfault.txt](https://github.com/Dugy/Legend_of_the_Invincibles/files/1799487/20180309.segfault.txt)

**Comment by matsjoyce** [comment]
A segfault is a wesnoth problem, so try reporting it at https://github.com/wesnoth/wesnoth

**Comment by Dugy** [comment]
Add-ons should not cause segfaults, because it is a security issue. No matter how bad the code is, it should not cause segfaults, because deliberately caused segfault can sometimes be used to edit any part of the program's memory, possibly even allowing a malicious add-on creator to hack the user's computer.

This campaign is quite likely to make undetected bugs appear because its complexity is makes it test a lot of rarely used features.

**Comment by alain-bkr** [comment]
This has been fixed in wesnoth
