### ISSUE TITLE
Some dialogs auto-dismissing in 1.18

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#820]
This is probably a wesnoth bug, but in 1.18, I notice that several times, when picking up items, the dialog is displayed and immediately goes away. Never noticed it on 1.16 before.

**Comment by arobinson** [comment]
[LotI2-Across the Barren Land-Auto-Save42.gz](https://github.com/user-attachments/files/15749275/LotI2-Across.the.Barren.Land-Auto-Save42.gz)
In the save 2 of 3 times, picking up the gem to the northeast of Efraim did not show the dialog and have it stay up

**Comment by Dugy** [comment]
I was able to replicate that, but with a lower probability than what you've described. If I observed that myself, I would have blamed it on my mouse being old and sometimes sending two click events instead of one.

I don't think there is a way an add-on could have caused this, this looks very much like a Wesnoth bug. My guess is that some click event persists in an event queue when it shouldn't.

**Comment by white-haired-uncle** [comment]
That's funny, I saw the same thing and blamed it on my mouse.

**Comment by arobinson** [comment]
Fixed with https://github.com/wesnoth/wesnoth/issues/9001
