### ISSUE TITLE
Can't find the right animation

### ISSUE THREAD

**Issue by arobinson** [Dugy/Legend_of_the_Invincibles#822]
The crossbows that add new attacks still give errors any time a Grand Marshal, Duke, etc. equip them or other equipment

```
<WML >: Warning: Couldn't find the right animation for unit sc05_general (2)
```

You can equip the crossbow on Aethyr to reproduce the error (it is in the item stash)

[LotI2-Across the Barren Land Turn 15.gz](https://github.com/user-attachments/files/15879379/LotI2-Across.the.Barren.Land.Turn.15.gz)

**Comment by Dugy** [comment]
The problem is that it's looking for a crossbow attack, and it uses the damage type to identify crossbow attacks. The damage of his crossbow attack is converted to cold, so there is no ranged pierce attack. Removing this restriction would allow basing these bonus crossbow attacks on spells, making the crossbows and even greater stat stick than they already are.

I will have to change the code how it is chosen, if I changed the item code to depend on attack name, the same problem would happen with orcish slurbows. The Searing Ice sword will choose whatever attack it finds is strongest, and it works because no unit has a sword and some other melee weapon, which is also a potential problem.

**Comment by Dugy** [comment]
I have changed the code that items granting bonus attacks will use the attacks that enable these units to use these weapons. That is, if the unit has a crossbow that grants bonus attacks, the attack will always be a crossbow attack. If the unit has a crossbow but doesn't have a crossbow attack (for example because it advanced from Death Knight to Infernal Knight), it will not gain any bonus attacks.
