### ISSUE TITLE
Lich can't enable/disable shadow wave if disabled before conversion to lich

### ISSUE THREAD

**Issue by Chergnobarp** [Dugy/Legend_of_the_Invincibles#841]
1. Read tome of liches 'til you get necromancy ability
2. Disable shadow wave for retaliation
3. Get the unit killed to transform it into a lich

If you bring up the lich's enable/disable attacks for retaliation dialog after that, shadow wave won't be there. It's not yet clear whether it's disabled or not. This doesn't affect chill wave -> chill tempest, so the easy solution seems to be to rename one of the attacks. Of course, that just tapes up the bug instead of fixing it.

The male prophet in this save can be used for a quick test. [LotI2-Another Orcish Assault Turn 5 pre-lich.gz](https://github.com/user-attachments/files/17152242/LotI2-Another.Orcish.Assault.Turn.5.pre-lich.gz)

**Comment by Discontinuum** [comment]
There is also #333. Afaik the problem is that the info about disabled attacks stored as just indexes of the attacks. Also there is some reservation to not confuse attacks with disabled retaliation and attacks that must not retaliate.  When a unit changes its type abruptly, this relative information might get very incorrect
