### ISSUE TITLE
Ghast and abomination loosing weapon usage

### ISSUE THREAD

**Issue by rodolphecombe** [Dugy/Legend_of_the_Invincibles#842]
Leveling up from necrophage, the ghast and abomination cannot use weapons anymore since bite is not a weapon type. 
One possibility would be to assign bite to an existing weapon type (claws or essence) or add a teeth/bite weapon type but it would add a weapon to other units (Skeletal Dragon to the least).

**Comment by Dugy** [comment]
That is intentional. Having a weapon type for bite attacks would be comical, I don't want to see any _Cruel Grandpa's Teeth of Bloodsucking._

The inability to equip weapons allows powerful weapon specials that would be quite overpowered if a weapon's bonuses could be applied over them. In case of Abomination, it's the weapon special that increases damage to poisoned enemies (also overall strong AMLA bonuses), in case of Skeletal Dragon, it's drain.

**Comment by rodolphecombe** [comment]
Thank you for the explanation
